# Exploratory Data Analysis

## Import Data and Libraries

In [1]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('./data/Flat prices.csv')

df

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0
...,...,...,...,...,...,...,...,...,...,...,...
92265,2021-02,YISHUN,EXECUTIVE,406,YISHUN AVE 6,10 TO 12,148.0,Maisonette,1988,66 years 08 months,655000.0
92266,2021-02,YISHUN,EXECUTIVE,355,YISHUN RING RD,10 TO 12,146.0,Maisonette,1988,66 years 10 months,650000.0
92267,2021-02,YISHUN,EXECUTIVE,364,YISHUN RING RD,01 TO 03,146.0,Maisonette,1988,66 years 02 months,607000.0
92268,2021-02,YISHUN,EXECUTIVE,828,YISHUN ST 81,01 TO 03,142.0,Apartment,1988,66 years,670000.0
92269,2021-02,YISHUN,EXECUTIVE,877,YISHUN ST 81,07 TO 09,145.0,Maisonette,1987,65 years 10 months,660000.0

## Data Quality Assessment

In [2]:
# Check for missing values
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
month                  0
town                   0
flat_type              0
block                  0
street_name            0
storey_range           0
floor_area_sqm         0
flat_model             0
lease_commence_date    0
remaining_lease        0
resale_price           0
dtype: int64

In [3]:
# Check data types
print("\nData Types:")
print(df.dtypes)

Data Types:
month                   object
town                    object
flat_type               object
block                   object
street_name             object
storey_range            object
floor_area_sqm         float64
flat_model              object
lease_commence_date      int64
remaining_lease         object
resale_price           float64
dtype: object

In [4]:
# Check for duplicates
print(f"\nDuplicate rows: {df.duplicated().sum()}")

Duplicate rows: 220

In [5]:
# Basic statistical summary
print("\nStatistical Summary:")
print(df.describe())

Statistical Summary:
       floor_area_sqm  lease_commence_date  resale_price
count    92270.000000         92270.000000  9.227000e+04
mean        97.768362          1994.444175  4.448869e+05
std         24.263575            13.064066  1.548243e+05
min         31.000000          1966.000000  1.400000e+05
25%         82.000000          1984.000000  3.330000e+05
50%         95.000000          1995.000000  4.150000e+05
75%        113.000000          2003.000000  5.200000e+05
max        249.000000          2019.000000  1.258000e+06

In [6]:
# Check unique values for categorical columns
categorical_cols = ['town', 'flat_type', 'flat_model', 'storey_range', 'street_name', 'block']
for col in categorical_cols:
    if col in df.columns:
        print(f"\nUnique values in {col} with the lowest counts:")
        print(df[col].value_counts().tail(10))

Unique values in town with the lowest counts:
town
QUEENSTOWN       2529
SEMBAWANG        2279
GEYLANG          2243
CLEMENTI         2112
JURONG EAST      2045
SERANGOON        1839
BISHAN           1821
CENTRAL AREA      755
MARINE PARADE     550
BUKIT TIMAH       255
Name: count, dtype: int64

Unique values in flat_type with the lowest counts:
flat_type
4 ROOM              38182
5 ROOM              23176
3 ROOM              21980
EXECUTIVE            7438
2 ROOM               1408
MULTI-GENERATION       44
1 ROOM                 42
Name: count, dtype: int64

Unique values in flat_model with the lowest counts:
flat_model
Adjoined flat             174
Model A-Maisonette        162
Type S1                   147
Type S2                    89
Terrace                    55
Multi Generation           44
Premium Apartment Loft     41
Improved-Maisonette        16
Premium Maisonette         11
2-room                      4
Name: count, dtype: int64

Unique values in storey_range with the lowest counts:
storey_range
22 TO 24    1289
25 TO 27     712
28 TO 30     447
31 TO 33     204
34 TO 36     198
37 TO 39     190
40 TO 42      97
46 TO 48      19
43 TO 45      16
49 TO 51       8
Name: count, dtype: int64

Unique values in street_name with the lowest counts:
street_name
TESSENSOHN RD         6
CLEMENTI ST 12        6
ANG MO KIO ST 21      6
KIM PONG RD           6
HENDERSON RD          5
JURONG WEST CTRL 3    5
BT MERAH LANE 1       3
KRETA AYER RD         3
SENG POH RD           2
SEMBAWANG WAY         1
Name: count, dtype: int64

Unique values in block with the lowest counts:
block
227D    1
905     1
96B     1
253A    1
860A    1
863B    1
697A    1
520B    1
380     1
225B    1
Name: count, dtype: int64

# Data Cleaning

In [7]:
# Create a copy for cleaning
df_clean = df.copy()

df_clean

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0
...,...,...,...,...,...,...,...,...,...,...,...
92265,2021-02,YISHUN,EXECUTIVE,406,YISHUN AVE 6,10 TO 12,148.0,Maisonette,1988,66 years 08 months,655000.0
92266,2021-02,YISHUN,EXECUTIVE,355,YISHUN RING RD,10 TO 12,146.0,Maisonette,1988,66 years 10 months,650000.0
92267,2021-02,YISHUN,EXECUTIVE,364,YISHUN RING RD,01 TO 03,146.0,Maisonette,1988,66 years 02 months,607000.0
92268,2021-02,YISHUN,EXECUTIVE,828,YISHUN ST 81,01 TO 03,142.0,Apartment,1988,66 years,670000.0
92269,2021-02,YISHUN,EXECUTIVE,877,YISHUN ST 81,07 TO 09,145.0,Maisonette,1987,65 years 10 months,660000.0

## Duplicate Records

In [8]:
# Remove duplicates
df_clean = df_clean.drop_duplicates()

print(f"After removing duplicates: {df_clean.shape}")
print(f"Duplicates removed: {df.shape[0] - df_clean.shape[0]}")

After removing duplicates: (92050, 11)
Duplicates removed: 220

In [9]:
df_clean

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0
...,...,...,...,...,...,...,...,...,...,...,...
92265,2021-02,YISHUN,EXECUTIVE,406,YISHUN AVE 6,10 TO 12,148.0,Maisonette,1988,66 years 08 months,655000.0
92266,2021-02,YISHUN,EXECUTIVE,355,YISHUN RING RD,10 TO 12,146.0,Maisonette,1988,66 years 10 months,650000.0
92267,2021-02,YISHUN,EXECUTIVE,364,YISHUN RING RD,01 TO 03,146.0,Maisonette,1988,66 years 02 months,607000.0
92268,2021-02,YISHUN,EXECUTIVE,828,YISHUN ST 81,01 TO 03,142.0,Apartment,1988,66 years,670000.0
92269,2021-02,YISHUN,EXECUTIVE,877,YISHUN ST 81,07 TO 09,145.0,Maisonette,1987,65 years 10 months,660000.0

## Drop Redundant Rows

In [10]:
# Drop 'month' and 'lease_commence_date' columns from df_clean
df_clean = df_clean.drop(columns=['month', 'lease_commence_date'], errors='ignore')
df_clean.head()

,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,remaining_lease,resale_price
0,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,61 years 04 months,232000.0
1,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,60 years 07 months,250000.0
2,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62 years 05 months,262000.0
3,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,62 years 01 month,265000.0
4,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62 years 05 months,265000.0

## Incorrect Data Types

### Remaining Lease Column

In [11]:
# Convert remaining_lease to numeric
def extract_lease_years(lease_str):
    if pd.isna(lease_str):
        return np.nan
    if isinstance(lease_str, (int, float)):
        return float(lease_str)
    try:
        lease_str_lower = str(lease_str).lower()
        # Handle formats like "62 y 05 months" - extract the first number
        if any(keyword in lease_str_lower for keyword in ['year', 'y', 'years', 'yrs']):
            # Extract the first number (years) - works for "62 y 05 months"
            years = int(lease_str_lower.split()[0])
            return years
        else:
            return float(lease_str)
    except:
        return np.nan

df_clean['remaining_lease'] = df_clean['remaining_lease'].apply(extract_lease_years)
print(f"Remaining lease range: {df_clean['remaining_lease'].min():.0f} to {df_clean['remaining_lease'].max():.0f} years")
print(f"Remaining lease missing values after conversion: {df_clean['remaining_lease'].isnull().sum()}")

Remaining lease range: 44 to 97 years
Remaining lease missing values after conversion: 0

In [12]:
df_clean

,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,remaining_lease,resale_price
0,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,61,232000.0
1,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,60,250000.0
2,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62,262000.0
3,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,62,265000.0
4,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62,265000.0
...,...,...,...,...,...,...,...,...,...
92265,YISHUN,EXECUTIVE,406,YISHUN AVE 6,10 TO 12,148.0,Maisonette,66,655000.0
92266,YISHUN,EXECUTIVE,355,YISHUN RING RD,10 TO 12,146.0,Maisonette,66,650000.0
92267,YISHUN,EXECUTIVE,364,YISHUN RING RD,01 TO 03,146.0,Maisonette,66,607000.0
92268,YISHUN,EXECUTIVE,828,YISHUN ST 81,01 TO 03,142.0,Apartment,66,670000.0
92269,YISHUN,EXECUTIVE,877,YISHUN ST 81,07 TO 09,145.0,Maisonette,65,660000.0

## Standardise Inconsistent Values

### Street Name Column

In [13]:
# Sort street names alphabetically and print counts
street_value_counts = df_clean['street_name'].value_counts()
street_value_counts_sorted = street_value_counts.sort_index()

print("All street names (Alphabetical):")
for street, count in street_value_counts_sorted.items():
  print(f"  {street}: {count} records")

print(f"Total number of distinct values {len(street_value_counts_sorted)}")

All street names (Alphabetical):
  ADMIRALTY DR: 391 records
  ADMIRALTY LINK: 311 records
  AH HOOD RD: 17 records
  ALJUNIED CRES: 166 records
  ALJUNIED RD: 14 records
  ANCHORVALE CRES: 153 records
  ANCHORVALE DR: 181 records
  ANCHORVALE LANE: 72 records
  ANCHORVALE LINK: 489 records
  ANCHORVALE RD: 368 records
  ANCHORVALE ST: 115 records
  ANG MO KIO AVE 1: 436 records
  ANG MO KIO AVE 10: 958 records
  ANG MO KIO AVE 2: 12 records
  ANG MO KIO AVE 3: 882 records
  ANG MO KIO AVE 4: 493 records
  ANG MO KIO AVE 5: 430 records
  ANG MO KIO AVE 6: 204 records
  ANG MO KIO AVE 8: 148 records
  ANG MO KIO AVE 9: 48 records
  ANG MO KIO ST 11: 14 records
  ANG MO KIO ST 21: 6 records
  ANG MO KIO ST 31: 75 records
  ANG MO KIO ST 32: 77 records
  ANG MO KIO ST 52: 273 records
  ANG MO KIO ST 61: 23 records
  BAIN ST: 17 records
  BALAM RD: 122 records
  BANGKIT RD: 134 records
  BEACH RD: 55 records
  BEDOK CTRL: 107 records
  BEDOK NTH AVE 1: 165 records
  BEDOK NTH AVE 2: 151 records
  BEDOK NTH AVE 3: 155 records
  BEDOK NTH AVE 4: 182 records
  BEDOK NTH RD: 563 records
  BEDOK NTH ST 1: 113 records
  BEDOK NTH ST 2: 153 records
  BEDOK NTH ST 3: 533 records
  BEDOK NTH ST 4: 38 records
  BEDOK RESERVOIR CRES: 80 records
  BEDOK RESERVOIR RD: 1054 records
  BEDOK RESERVOIR VIEW: 180 records
  BEDOK STH AVE 1: 80 records
  BEDOK STH AVE 2: 169 records
  BEDOK STH AVE 3: 91 records
  BEDOK STH RD: 190 records
  BENDEMEER RD: 225 records
  BEO CRES: 45 records
  BISHAN ST 11: 63 records
  BISHAN ST 12: 376 records
  BISHAN ST 13: 367 records
  BISHAN ST 22: 252 records
  BISHAN ST 23: 160 records
  BISHAN ST 24: 270 records
  BOON KENG RD: 188 records
  BOON LAY AVE: 241 records
  BOON LAY DR: 423 records
  BOON LAY PL: 223 records
  BOON TIONG RD: 169 records
  BRIGHT HILL DR: 22 records
  BT BATOK CTRL: 195 records
  BT BATOK EAST AVE 3: 129 records
  BT BATOK EAST AVE 4: 182 records
  BT BATOK EAST AVE 5: 247 records
  BT BATOK ST 11: 126 records
  BT BATOK ST 21: 212 records
  BT BATOK ST 22: 19 records
  BT BATOK ST 24: 127 records
  BT BATOK ST 25: 149 records
  BT BATOK ST 31: 184 records
  BT BATOK ST 32: 118 records
  BT BATOK ST 33: 107 records
  BT BATOK ST 34: 140 records
  BT BATOK ST 51: 67 records
  BT BATOK ST 52: 216 records
  BT BATOK WEST AVE 2: 57 records
  BT BATOK WEST AVE 4: 89 records
  BT BATOK WEST AVE 5: 285 records
  BT BATOK WEST AVE 6: 400 records
  BT BATOK WEST AVE 7: 21 records
  BT BATOK WEST AVE 8: 180 records
  BT MERAH CTRL: 29 records
  BT MERAH LANE 1: 3 records
  BT MERAH VIEW: 127 records
  BT PANJANG RING RD: 319 records
  BT PURMEI RD: 140 records
  BUANGKOK CRES: 224 records
  BUANGKOK GREEN: 141 records
  BUANGKOK LINK: 52 records
  BUFFALO RD: 21 records
  C'WEALTH AVE: 13 records
  C'WEALTH AVE WEST: 50 records
  C'WEALTH CL: 132 records
  C'WEALTH CRES: 94 records
  C'WEALTH DR: 173 records
  CAMBRIDGE RD: 37 records
  CANBERRA LINK: 45 records
  CANBERRA RD: 283 records
  CANTONMENT CL: 119 records
  CANTONMENT RD: 236 records
  CASHEW RD: 61 records
  CASSIA CRES: 95 records
  CHAI CHEE AVE: 89 records
  CHAI CHEE DR: 50 records
  CHAI CHEE RD: 232 records
  CHAI CHEE ST: 156 records
  CHANDER RD: 9 records
  CHANGI VILLAGE RD: 22 records
  CHIN SWEE RD: 7 records
  CHOA CHU KANG AVE 1: 88 records
  CHOA CHU KANG AVE 2: 174 records
  CHOA CHU KANG AVE 3: 246 records
  CHOA CHU KANG AVE 4: 376 records
  CHOA CHU KANG AVE 5: 422 records
  CHOA CHU KANG AVE 7: 14 records
  CHOA CHU KANG CRES: 679 records
  CHOA CHU KANG CTRL: 200 records
  CHOA CHU KANG DR: 136 records
  CHOA CHU KANG LOOP: 25 records
  CHOA CHU KANG NTH 5: 96 records
  CHOA CHU KANG NTH 6: 122 records
  CHOA CHU KANG NTH 7: 20 records
  CHOA CHU KANG ST 51: 156 records
  CHOA CHU KANG ST 52: 184 records
  CHOA CHU KANG ST 53: 51 records
  CHOA CHU KANG ST 54: 47 records
  CHOA CHU KANG ST 62: 159 records
  CHOA CHU KANG ST 64: 48 records
  CIRCUIT RD: 468 records
  CLARENCE LANE: 35 records
  CLEMENTI AVE 1: 247 records
  CLEMENTI AVE 2: 236 records
  CLEMENTI AVE 3: 252 records
  CLEMENTI AVE 4: 404 records
  CLEMENTI AVE 5: 180 records
  CLEMENTI AVE 6: 47 records
  CLEMENTI ST 11: 8 records
  CLEMENTI ST 12: 6 records
  CLEMENTI ST 13: 70 records
  CLEMENTI ST 14: 17 records
  CLEMENTI WEST ST 1: 163 records
  CLEMENTI WEST ST 2: 250 records
  COMPASSVALE BOW: 73 records
  COMPASSVALE CRES: 159 records
  COMPASSVALE DR: 193 records
  COMPASSVALE LANE: 383 records
  COMPASSVALE LINK: 316 records
  COMPASSVALE RD: 211 records
  COMPASSVALE ST: 319 records
  COMPASSVALE WALK: 194 records
  CORPORATION DR: 33 records
  CRAWFORD LANE: 34 records
  DAKOTA CRES: 35 records
  DAWSON RD: 201 records
  DELTA AVE: 42 records
  DEPOT RD: 131 records
  DORSET RD: 34 records
  DOVER CL EAST: 23 records
  DOVER CRES: 220 records
  DOVER RD: 26 records
  EDGEDALE PLAINS: 349 records
  EDGEFIELD PLAINS: 703 records
  ELIAS RD: 81 records
  EMPRESS RD: 19 records
  EUNOS CRES: 263 records
  EUNOS RD 5: 32 records
  EVERTON PK: 44 records
  FAJAR RD: 299 records
  FARRER PK RD: 94 records
  FARRER RD: 13 records
  FERNVALE LANE: 113 records
  FERNVALE LINK: 570 records
  FERNVALE RD: 913 records
  FERNVALE ST: 96 records
  FRENCH RD: 8 records
  GANGSA RD: 191 records
  GEYLANG BAHRU: 214 records
  GEYLANG EAST AVE 1: 79 records
  GEYLANG EAST CTRL: 27 records
  GEYLANG SERAI: 79 records
  GHIM MOH LINK: 160 records
  GHIM MOH RD: 182 records
  GLOUCESTER RD: 19 records
  HAIG RD: 127 records
  HAVELOCK RD: 190 records
  HENDERSON CRES: 52 records
  HENDERSON RD: 5 records
  HO CHING RD: 88 records
  HOLLAND AVE: 145 records
  HOLLAND CL: 125 records
  HOLLAND DR: 182 records
  HOUGANG AVE 1: 287 records
  HOUGANG AVE 10: 296 records
  HOUGANG AVE 2: 114 records
  HOUGANG AVE 3: 212 records
  HOUGANG AVE 4: 141 records
  HOUGANG AVE 5: 253 records
  HOUGANG AVE 6: 161 records
  HOUGANG AVE 7: 111 records
  HOUGANG AVE 8: 645 records
  HOUGANG AVE 9: 164 records
  HOUGANG CTRL: 98 records
  HOUGANG ST 11: 69 records
  HOUGANG ST 21: 59 records
  HOUGANG ST 22: 67 records
  HOUGANG ST 31: 46 records
  HOUGANG ST 32: 15 records
  HOUGANG ST 51: 243 records
  HOUGANG ST 52: 83 records
  HOUGANG ST 61: 93 records
  HOUGANG ST 91: 265 records
  HOUGANG ST 92: 71 records
  HOY FATT RD: 34 records
  INDUS RD: 17 records
  JELAPANG RD: 389 records
  JELEBU RD: 102 records
  JELLICOE RD: 29 records
  JLN BAHAGIA: 122 records
  JLN BATU: 95 records
  JLN BERSEH: 7 records
  JLN BT HO SWEE: 40 records
  JLN BT MERAH: 225 records
  JLN DAMAI: 64 records
  JLN DUA: 13 records
  JLN DUSUN: 15 records
  JLN KAYU: 100 records
  JLN KLINIK: 39 records
  JLN KUKOH: 25 records
  JLN MA'MOR: 20 records
  JLN MEMBINA: 274 records
  JLN RAJAH: 80 records
  JLN RUMAH TINGGI: 87 records
  JLN TECK WHYE: 118 records
  JLN TENAGA: 105 records
  JLN TENTERAM: 78 records
  JLN TIGA: 34 records
  JOO CHIAT RD: 12 records
  JOO SENG RD: 91 records
  JURONG EAST AVE 1: 121 records
  JURONG EAST ST 13: 108 records
  JURONG EAST ST 21: 426 records
  JURONG EAST ST 24: 267 records
  JURONG EAST ST 31: 90 records
  JURONG EAST ST 32: 233 records
  JURONG WEST AVE 1: 232 records
  JURONG WEST AVE 3: 97 records
  JURONG WEST AVE 5: 75 records
  JURONG WEST CTRL 1: 262 records
  JURONG WEST CTRL 3: 5 records
  JURONG WEST ST 24: 95 records
  JURONG WEST ST 25: 137 records
  JURONG WEST ST 41: 292 records
  JURONG WEST ST 42: 415 records
  JURONG WEST ST 51: 8 records
  JURONG WEST ST 52: 338 records
  JURONG WEST ST 61: 459 records
  JURONG WEST ST 62: 53 records
  JURONG WEST ST 64: 529 records
  JURONG WEST ST 65: 621 records
  JURONG WEST ST 71: 108 records
  JURONG WEST ST 72: 21 records
  JURONG WEST ST 73: 91 records
  JURONG WEST ST 74: 68 records
  JURONG WEST ST 75: 25 records
  JURONG WEST ST 81: 405 records
  JURONG WEST ST 91: 296 records
  JURONG WEST ST 92: 107 records
  JURONG WEST ST 93: 246 records
  KALLANG BAHRU: 80 records
  KANG CHING RD: 148 records
  KEAT HONG CL: 23 records
  KELANTAN RD: 32 records
  KENT RD: 27 records
  KG ARANG RD: 19 records
  KG KAYU RD: 10 records
  KIM CHENG ST: 12 records
  KIM KEAT AVE: 93 records
  KIM KEAT LINK: 55 records
  KIM PONG RD: 6 records
  KIM TIAN PL: 51 records
  KIM TIAN RD: 258 records
  KING GEORGE'S AVE: 31 records
  KLANG LANE: 53 records
  KRETA AYER RD: 3 records
  LENGKOK BAHRU: 79 records
  LENGKONG TIGA: 81 records
  LIM LIAK ST: 13 records
  LOMPANG RD: 108 records
  LOR 1 TOA PAYOH: 415 records
  LOR 1A TOA PAYOH: 335 records
  LOR 2 TOA PAYOH: 298 records
  LOR 3 GEYLANG: 14 records
  LOR 3 TOA PAYOH: 33 records
  LOR 4 TOA PAYOH: 207 records
  LOR 5 TOA PAYOH: 175 records
  LOR 6 TOA PAYOH: 51 records
  LOR 7 TOA PAYOH: 267 records
  LOR 8 TOA PAYOH: 261 records
  LOR AH SOO: 148 records
  LOR LEW LIAN: 87 records
  LOR LIMAU: 45 records
  LOWER DELTA RD: 11 records
  MACPHERSON LANE: 13 records
  MARINE CRES: 196 records
  MARINE DR: 161 records
  MARINE TER: 188 records
  MARSILING CRES: 38 records
  MARSILING DR: 450 records
  MARSILING LANE: 230 records
  MARSILING RD: 69 records
  MARSILING RISE: 136 records
  MCNAIR RD: 119 records
  MEI LING ST: 147 records
  MOH GUAN TER: 21 records
  MONTREAL DR: 91 records
  MONTREAL LINK: 171 records
  MOULMEIN RD: 7 records
  NEW MKT RD: 7 records
  NEW UPP CHANGI RD: 225 records
  NTH BRIDGE RD: 34 records
  OLD AIRPORT RD: 17 records
  OWEN RD: 10 records
  PANDAN GDNS: 137 records
  PASIR RIS DR 1: 101 records
  PASIR RIS DR 10: 116 records
  PASIR RIS DR 3: 73 records
  PASIR RIS DR 4: 175 records
  PASIR RIS DR 6: 317 records
  PASIR RIS ST 11: 300 records
  PASIR RIS ST 12: 146 records
  PASIR RIS ST 13: 47 records
  PASIR RIS ST 21: 343 records
  PASIR RIS ST 41: 15 records
  PASIR RIS ST 51: 480 records
  PASIR RIS ST 52: 122 records
  PASIR RIS ST 53: 79 records
  PASIR RIS ST 71: 345 records
  PASIR RIS ST 72: 83 records
  PAYA LEBAR WAY: 75 records
  PENDING RD: 186 records
  PETIR RD: 246 records
  PINE CL: 92 records
  PIPIT RD: 48 records
  POTONG PASIR AVE 1: 235 records
  POTONG PASIR AVE 2: 33 records
  POTONG PASIR AVE 3: 56 records
  PUNGGOL CTRL: 843 records
  PUNGGOL DR: 988 records
  PUNGGOL EAST: 59 records
  PUNGGOL FIELD: 1041 records
  PUNGGOL FIELD WALK: 44 records
  PUNGGOL PL: 871 records
  PUNGGOL RD: 172 records
  PUNGGOL WALK: 678 records
  PUNGGOL WAY: 277 records
  QUEEN ST: 21 records
  QUEEN'S CL: 34 records
  QUEEN'S RD: 52 records
  QUEENSWAY: 20 records
  RACE COURSE RD: 35 records
  REDHILL CL: 63 records
  REDHILL LANE: 21 records
  REDHILL RD: 153 records
  RIVERVALE CRES: 666 records
  RIVERVALE DR: 476 records
  RIVERVALE ST: 146 records
  RIVERVALE WALK: 119 records
  ROWELL RD: 36 records
  SAGO LANE: 20 records
  SAUJANA RD: 36 records
  SEGAR RD: 848 records
  SELEGIE RD: 37 records
  SEMBAWANG CL: 235 records
  SEMBAWANG CRES: 63 records
  SEMBAWANG DR: 430 records
  SEMBAWANG VISTA: 48 records
  SEMBAWANG WAY: 1 records
  SENG POH RD: 2 records
  SENGKANG CTRL: 142 records
  SENGKANG EAST AVE: 204 records
  SENGKANG EAST RD: 54 records
  SENGKANG EAST WAY: 220 records
  SENGKANG WEST AVE: 91 records
  SENGKANG WEST WAY: 416 records
  SENJA LINK: 45 records
  SENJA RD: 748 records
  SERANGOON AVE 1: 67 records
  SERANGOON AVE 2: 210 records
  SERANGOON AVE 3: 175 records
  SERANGOON AVE 4: 210 records
  SERANGOON CTRL: 188 records
  SERANGOON CTRL DR: 52 records
  SERANGOON NTH AVE 1: 318 records
  SERANGOON NTH AVE 2: 50 records
  SERANGOON NTH AVE 3: 105 records
  SERANGOON NTH AVE 4: 375 records
  SHUNFU RD: 100 records
  SILAT AVE: 26 records
  SIMEI LANE: 92 records
  SIMEI RD: 58 records
  SIMEI ST 1: 364 records
  SIMEI ST 2: 44 records
  SIMEI ST 4: 93 records
  SIMEI ST 5: 32 records
  SIMS AVE: 23 records
  SIMS DR: 66 records
  SIMS PL: 25 records
  SIN MING AVE: 157 records
  SIN MING RD: 49 records
  SMITH ST: 18 records
  SPOTTISWOODE PK RD: 39 records
  ST. GEORGE'S LANE: 67 records
  ST. GEORGE'S RD: 146 records
  STIRLING RD: 159 records
  STRATHMORE AVE: 323 records
  SUMANG LINK: 116 records
  SUMANG WALK: 40 records
  TAH CHING RD: 120 records
  TAMAN HO SWEE: 32 records
  TAMPINES AVE 1: 67 records
  TAMPINES AVE 4: 170 records
  TAMPINES AVE 5: 157 records
  TAMPINES AVE 7: 30 records
  TAMPINES AVE 8: 150 records
  TAMPINES AVE 9: 138 records
  TAMPINES CTRL 1: 22 records
  TAMPINES CTRL 7: 317 records
  TAMPINES CTRL 8: 84 records
  TAMPINES ST 11: 195 records
  TAMPINES ST 12: 184 records
  TAMPINES ST 21: 495 records
  TAMPINES ST 22: 326 records
  TAMPINES ST 23: 119 records
  TAMPINES ST 24: 84 records
  TAMPINES ST 32: 162 records
  TAMPINES ST 33: 234 records
  TAMPINES ST 34: 134 records
  TAMPINES ST 41: 304 records
  TAMPINES ST 42: 155 records
  TAMPINES ST 43: 148 records
  TAMPINES ST 44: 72 records
  TAMPINES ST 45: 232 records
  TAMPINES ST 71: 308 records
  TAMPINES ST 72: 124 records
  TAMPINES ST 81: 244 records
  TAMPINES ST 82: 176 records
  TAMPINES ST 83: 275 records
  TAMPINES ST 84: 115 records
  TAMPINES ST 86: 32 records
  TAMPINES ST 91: 173 records
  TANGLIN HALT RD: 134 records
  TAO CHING RD: 8 records
  TEBAN GDNS RD: 392 records
  TECK WHYE AVE: 82 records
  TECK WHYE CRES: 25 records
  TECK WHYE LANE: 321 records
  TELOK BLANGAH CRES: 280 records
  TELOK BLANGAH DR: 200 records
  TELOK BLANGAH HTS: 195 records
  TELOK BLANGAH RISE: 97 records
  TELOK BLANGAH ST 31: 112 records
  TELOK BLANGAH WAY: 33 records
  TESSENSOHN RD: 6 records
  TG PAGAR PLAZA: 84 records
  TIONG BAHRU RD: 19 records
  TOA PAYOH CTRL: 163 records
  TOA PAYOH EAST: 55 records
  TOA PAYOH NTH: 160 records
  TOH GUAN RD: 265 records
  TOH YI DR: 171 records
  TOWNER RD: 52 records
  UBI AVE 1: 311 records
  UPP ALJUNIED LANE: 33 records
  UPP BOON KENG RD: 234 records
  UPP CROSS ST: 59 records
  UPP SERANGOON CRES: 243 records
  UPP SERANGOON RD: 17 records
  UPP SERANGOON VIEW: 127 records
  VEERASAMY RD: 38 records
  WATERLOO ST: 21 records
  WELLINGTON CIRCLE: 206 records
  WEST COAST DR: 96 records
  WEST COAST RD: 84 records
  WHAMPOA DR: 200 records
  WHAMPOA RD: 54 records
  WHAMPOA STH: 17 records
  WHAMPOA WEST: 35 records
  WOODLANDS AVE 1: 339 records
  WOODLANDS AVE 3: 24 records
  WOODLANDS AVE 4: 149 records
  WOODLANDS AVE 5: 73 records
  WOODLANDS AVE 6: 235 records
  WOODLANDS AVE 9: 18 records
  WOODLANDS CIRCLE: 360 records
  WOODLANDS CRES: 455 records
  WOODLANDS DR 14: 361 records
  WOODLANDS DR 16: 272 records
  WOODLANDS DR 40: 76 records
  WOODLANDS DR 42: 47 records
  WOODLANDS DR 44: 64 records
  WOODLANDS DR 50: 418 records
  WOODLANDS DR 52: 99 records
  WOODLANDS DR 53: 53 records
  WOODLANDS DR 60: 136 records
  WOODLANDS DR 62: 106 records
  WOODLANDS DR 70: 93 records
  WOODLANDS DR 71: 44 records
  WOODLANDS DR 72: 48 records
  WOODLANDS DR 73: 148 records
  WOODLANDS DR 75: 310 records
  WOODLANDS RING RD: 414 records
  WOODLANDS ST 11: 28 records
  WOODLANDS ST 13: 361 records
  WOODLANDS ST 31: 118 records
  WOODLANDS ST 32: 86 records
  WOODLANDS ST 41: 246 records
  WOODLANDS ST 81: 117 records
  WOODLANDS ST 82: 199 records
  WOODLANDS ST 83: 176 records
  YISHUN AVE 1: 152 records
  YISHUN AVE 11: 806 records
  YISHUN AVE 2: 69 records
  YISHUN AVE 3: 97 records
  YISHUN AVE 4: 189 records
  YISHUN AVE 5: 272 records
  YISHUN AVE 6: 267 records
  YISHUN AVE 7: 70 records
  YISHUN AVE 9: 296 records
  YISHUN CTRL: 107 records
  YISHUN CTRL 1: 20 records
  YISHUN RING RD: 1373 records
  YISHUN ST 11: 341 records
  YISHUN ST 20: 42 records
  YISHUN ST 21: 331 records
  YISHUN ST 22: 224 records
  YISHUN ST 31: 224 records
  YISHUN ST 41: 165 records
  YISHUN ST 51: 142 records
  YISHUN ST 61: 341 records
  YISHUN ST 71: 201 records
  YISHUN ST 72: 226 records
  YISHUN ST 81: 314 records
  YUAN CHING RD: 103 records
  YUNG AN RD: 43 records
  YUNG HO RD: 29 records
  YUNG KUANG RD: 57 records
  YUNG LOH RD: 19 records
  YUNG PING RD: 35 records
  YUNG SHENG RD: 80 records
  ZION RD: 10 records
Total number of distinct values 551

In [14]:
# Define mapping for street_name standardization
street_name_mapping = {
    # ANG MO KIO abbreviations
    'AMK AVE 10': 'ANG MO KIO AVE 10',
    'AMK AVE 1': 'ANG MO KIO AVE 1',
    'AMK AVE 2': 'ANG MO KIO AVE 2',
    'AMK AVE 3': 'ANG MO KIO AVE 3',
    'AMK AVE 4': 'ANG MO KIO AVE 4',
    'AMK AVE 5': 'ANG MO KIO AVE 5',
    'AMK AVE 6': 'ANG MO KIO AVE 6',
    'AMK AVE 8': 'ANG MO KIO AVE 8',
    'AMK AVE 9': 'ANG MO KIO AVE 9',
    
    # TOA PAYOH abbreviations
    'LOR 2 TP': 'LOR 2 TOA PAYOH',
    'LOR 7 TP': 'LOR 7 TOA PAYOH', 
    'LOR 8 TP': 'LOR 8 TOA PAYOH',
    
    # Directional abbreviations
    'BEDOK NTH AVE 1': 'BEDOK NORTH AVE 1',
    'BEDOK NTH AVE 2': 'BEDOK NORTH AVE 2',
    'BEDOK NTH AVE 3': 'BEDOK NORTH AVE 3',
    'BEDOK NTH AVE 4': 'BEDOK NORTH AVE 4',
    'BEDOK NTH RD': 'BEDOK NORTH RD',
    'BEDOK NTH ST 1': 'BEDOK NORTH ST 1',
    'BEDOK NTH ST 2': 'BEDOK NORTH ST 2',
    'BEDOK NTH ST 3': 'BEDOK NORTH ST 3',
    'BEDOK NTH ST 4': 'BEDOK NORTH ST 4',
    'BEDOK STH AVE 1': 'BEDOK SOUTH AVE 1',
    'BEDOK STH AVE 2': 'BEDOK SOUTH AVE 2',
    'BEDOK STH AVE 3': 'BEDOK SOUTH AVE 3',
    'BEDOK STH RD': 'BEDOK SOUTH RD',
    
    # CENTRAL abbreviations
    'BEDOK CTRL': 'BEDOK CENTRAL',
    'BT BATOK CTRL': 'BUKIT BATOK CENTRAL',
    'CHOA CHU KANG CTRL': 'CHOA CHU KANG CENTRAL',
    'HOUGANG CTRL': 'HOUGANG CENTRAL',
    'JURONG WEST CTRL 1': 'JURONG WEST CENTRAL 1',
    'JURONG WEST CTRL 3': 'JURONG WEST CENTRAL 3',
    'SENGKANG CTRL': 'SENGKANG CENTRAL',
    'SERANGOON CTRL': 'SERANGOON CENTRAL',
    'SERANGOON CTRL DR': 'SERANGOON CENTRAL DR',
    'TAMPINES CTRL 1': 'TAMPINES CENTRAL 1',
    'TAMPINES CTRL 7': 'TAMPINES CENTRAL 7',
    'TAMPINES CTRL 8': 'TAMPINES CENTRAL 8',
    'TOA PAYOH CTRL': 'TOA PAYOH CENTRAL',
    'YISHUN CTRL': 'YISHUN CENTRAL',
    'YISHUN CTRL 1': 'YISHUN CENTRAL 1',
    
    # Common abbreviations
    'C\'WEALTH AVE': 'COMMONWEALTH AVE',
    'C\'WEALTH AVE WEST': 'COMMONWEALTH AVE WEST',
    'C\'WEALTH CL': 'COMMONWEALTH CL',
    'C\'WEALTH CRES': 'COMMONWEALTH CRES',
    'C\'WEALTH DR': 'COMMONWEALTH DR',
    
    # BT -> BUKIT
    'BT BATOK EAST AVE 3': 'BUKIT BATOK EAST AVE 3',
    'BT BATOK EAST AVE 4': 'BUKIT BATOK EAST AVE 4',
    'BT BATOK EAST AVE 5': 'BUKIT BATOK EAST AVE 5',
    'BT BATOK EAST AVE 6': 'BUKIT BATOK EAST AVE 6',
    'BT BATOK WEST AVE 2': 'BUKIT BATOK WEST AVE 2',
    'BT BATOK WEST AVE 4': 'BUKIT BATOK WEST AVE 4',
    'BT BATOK WEST AVE 5': 'BUKIT BATOK WEST AVE 5',
    'BT BATOK WEST AVE 6': 'BUKIT BATOK WEST AVE 6',
    'BT BATOK WEST AVE 7': 'BUKIT BATOK WEST AVE 7',
    'BT BATOK WEST AVE 8': 'BUKIT BATOK WEST AVE 8',
    'BT BATOK WEST AVE 9': 'BUKIT BATOK WEST AVE 9',
    'BT MERAH CTRL': 'BUKIT MERAH CENTRAL',
    'BT MERAH LANE 1': 'BUKIT MERAH LANE 1',
    'BT MERAH VIEW': 'BUKIT MERAH VIEW',
    'BT PANJANG RING RD': 'BUKIT PANJANG RING RD',
    'BT PURMEI RD': 'BUKIT PURMEI RD',
    
    # JLN -> JALAN
    'JLN BAHAGIA': 'JALAN BAHAGIA',
    'JLN BATU': 'JALAN BATU',
    'JLN BERSEH': 'JALAN BERSEH',
    'JLN BT HO SWEE': 'JALAN BUKIT HO SWEE',
    'JLN BT MERAH': 'JALAN BUKIT MERAH',
    'JLN BT MERAH BT MERAH': 'JALAN BUKIT MERAH',  # Remove duplicate
    'JLN DAMAI': 'JALAN DAMAI',
    'JLN DUA': 'JALAN DUA',
    'JLN DUSUN': 'JALAN DUSUN',
    'JLN KAYU': 'JALAN KAYU',
    'JLN KLINIK': 'JALAN KLINIK',
    'JLN KUKOH': 'JALAN KUKOH',
    'JLN MA\'MOR': 'JALAN MA\'MOR',
    'JLN MEMBINA': 'JALAN MEMBINA',
    'JLN RAJAH': 'JALAN RAJAH',
    'JLN RUMAH TINGGI': 'JALAN RUMAH TINGGI',
    'JLN TECK WHYE': 'JALAN TECK WHYE',
    'JLN TENAGA': 'JALAN TENAGA',
    'JLN TENTERAM': 'JALAN TENTERAM',
    'JLN TIGA': 'JALAN TIGA',
    
    # Other common abbreviations
    'NTH BRIDGE RD': 'NORTH BRIDGE RD',
    'NEW MKT RD': 'NEW MARKET RD',
    'UPP CHANGI RD': 'UPPER CHANGI RD',
    'TG PAGAR PLAZA': 'TANJONG PAGAR PLAZA',
    
    # Remove duplicates and typos
    'CANTONMENT CL CL': 'CANTONMENT CL',
    'FERNVALE LINK LINK': 'FERNVALE LINK',
    'SENGKANG EAST WAY LINK': 'SENGKANG EAST WAY',
    'TAMPINES CTeRL 1': 'TAMPINES CENTRAL 1',
    'TAMPINES CTeRL 7': 'TAMPINES CENTRAL 7', 
    'TAMPINES CeRL 7': 'TAMPINES CENTRAL 7',
    'KIM TIAN RD Spore': 'KIM TIAN RD'
}

# Apply the mapping to standardize street_name
df_clean['street_name'] = df_clean['street_name'].replace(street_name_mapping)

print("After standardization:")
print(df_clean['street_name'].value_counts())
print(f"Total number of distinct values {len(df_clean['street_name'].value_counts())}")

# Sum counts of the removed distinct values (keys present in street_value_counts)
mapping_keys = set(street_name_mapping.keys())
present_keys = street_value_counts.index.intersection(mapping_keys)

removed_counts = street_value_counts.loc[present_keys]
affected_rows = int(removed_counts.sum())

# Optional: dataframe of affected rows (rows whose original street_name was one of the mapped keys)
affected_rows_df = df_clean[df_clean['street_name'].isin(present_keys)].copy()

print(f"Distinct mapped keys present: {len(present_keys)}")
print(removed_counts.sort_values(ascending=False))
print(f"Total rows affected by mapping: {affected_rows}")

After standardization:
street_name
YISHUN RING RD           1373
BEDOK RESERVOIR RD       1054
PUNGGOL FIELD            1041
PUNGGOL DR                988
ANG MO KIO AVE 10         958
                         ...
JURONG WEST CENTRAL 3       5
KRETA AYER RD               3
BUKIT MERAH LANE 1          3
SENG POH RD                 2
SEMBAWANG WAY               1
Name: count, Length: 551, dtype: int64
Total number of distinct values 551
Distinct mapped keys present: 69
street_name
BEDOK NTH RD           563
BEDOK NTH ST 3         533
BT BATOK WEST AVE 6    400
BT PANJANG RING RD     319
TAMPINES CTRL 7        317
                      ...
C'WEALTH AVE            13
NEW MKT RD               7
JLN BERSEH               7
JURONG WEST CTRL 3       5
BT MERAH LANE 1          3
Name: count, Length: 69, dtype: int64
Total rows affected by mapping: 8881

In [15]:
df_clean

,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,remaining_lease,resale_price
0,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,61,232000.0
1,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,60,250000.0
2,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62,262000.0
3,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,62,265000.0
4,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62,265000.0
...,...,...,...,...,...,...,...,...,...
92265,YISHUN,EXECUTIVE,406,YISHUN AVE 6,10 TO 12,148.0,Maisonette,66,655000.0
92266,YISHUN,EXECUTIVE,355,YISHUN RING RD,10 TO 12,146.0,Maisonette,66,650000.0
92267,YISHUN,EXECUTIVE,364,YISHUN RING RD,01 TO 03,146.0,Maisonette,66,607000.0
92268,YISHUN,EXECUTIVE,828,YISHUN ST 81,01 TO 03,142.0,Apartment,66,670000.0
92269,YISHUN,EXECUTIVE,877,YISHUN ST 81,07 TO 09,145.0,Maisonette,65,660000.0

## Check the Final Cleaned Dataset

In [16]:
# Check for duplicate rows in df_clean
duplicate_count = df_clean.duplicated().sum()
print(f"Number of duplicate rows in df_clean: {duplicate_count}")

Number of duplicate rows in df_clean: 894

In [17]:
df_clean = df_clean.drop_duplicates()
print(f"Rows after dropping duplicates: {len(df_clean):,}")

Rows after dropping duplicates: 91,156

In [18]:
# Check for missing values
print("Missing Values:")
print(df_clean.isnull().sum())

# Check data types
print("\nData Types:")
print(df_clean.dtypes)

# Basic statistical summary
print("\nStatistical Summary:")
print(df_clean.describe())

# Check unique values for categorical columns
categorical_cols = ['town', 'flat_type', 'flat_model', 'storey_range']
for col in categorical_cols:
    if col in df_clean.columns:
        print(f"\nUnique values in {col}:")
        print(df_clean[col].value_counts().head(10))

Missing Values:
town               0
flat_type          0
block              0
street_name        0
storey_range       0
floor_area_sqm     0
flat_model         0
remaining_lease    0
resale_price       0
dtype: int64

Data Types:
town                object
flat_type           object
block               object
street_name         object
storey_range        object
floor_area_sqm     float64
flat_model          object
remaining_lease      int64
resale_price       float64
dtype: object

Statistical Summary:
       floor_area_sqm  remaining_lease  resale_price
count    91156.000000     91156.000000  9.115600e+04
mean        97.867587        74.274178  4.453071e+05
std         24.271445        12.987281  1.550651e+05
min         31.000000        44.000000  1.400000e+05
25%         82.000000        64.000000  3.350000e+05
50%         95.000000        74.000000  4.150000e+05
75%        113.000000        84.000000  5.210000e+05
max        249.000000        97.000000  1.258000e+06

Unique values in town:
town
SENGKANG         7458
JURONG WEST      6590
WOODLANDS        6525
YISHUN           6180
PUNGGOL          6093
TAMPINES         6079
BEDOK            4947
HOUGANG          4406
ANG MO KIO       4044
CHOA CHU KANG    3786
Name: count, dtype: int64

Unique values in flat_type:
flat_type
4 ROOM              37695
5 ROOM              22975
3 ROOM              21634
EXECUTIVE            7394
2 ROOM               1377
MULTI-GENERATION       43
1 ROOM                 38
Name: count, dtype: int64

Unique values in flat_model:
flat_model
Model A              29725
Improved             22842
New Generation       12299
Premium Apartment     9995
Apartment             3748
Simplified            3715
Maisonette            2766
Standard              2593
DBSS                  1596
Model A2              1137
Name: count, dtype: int64

Unique values in storey_range:
storey_range
04 TO 06    21118
07 TO 09    19146
10 TO 12    17077
01 TO 03    16468
13 TO 15     8560
16 TO 18     3925
19 TO 21     1719
22 TO 24     1276
25 TO 27      699
28 TO 30      442
Name: count, dtype: int64

In [19]:
df_clean

,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,remaining_lease,resale_price
0,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,61,232000.0
1,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,60,250000.0
2,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62,262000.0
3,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,62,265000.0
4,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62,265000.0
...,...,...,...,...,...,...,...,...,...
92265,YISHUN,EXECUTIVE,406,YISHUN AVE 6,10 TO 12,148.0,Maisonette,66,655000.0
92266,YISHUN,EXECUTIVE,355,YISHUN RING RD,10 TO 12,146.0,Maisonette,66,650000.0
92267,YISHUN,EXECUTIVE,364,YISHUN RING RD,01 TO 03,146.0,Maisonette,66,607000.0
92268,YISHUN,EXECUTIVE,828,YISHUN ST 81,01 TO 03,142.0,Apartment,66,670000.0
92269,YISHUN,EXECUTIVE,877,YISHUN ST 81,07 TO 09,145.0,Maisonette,65,660000.0

In [20]:
# Print the number of unique values for each column in df_clean
for col in df_clean.columns:
  unique_count = df_clean[col].nunique(dropna=True)
  print(f"{col}: {unique_count} unique values")

town: 26 unique values
flat_type: 7 unique values
block: 2491 unique values
street_name: 551 unique values
storey_range: 17 unique values
floor_area_sqm: 162 unique values
flat_model: 20 unique values
remaining_lease: 54 unique values
resale_price: 2634 unique values

# Geocoding

## Create Address Column

In [21]:
df_clean['address'] = df_clean["block"].astype(str) + " " + df_clean["street_name"]
df_clean

C:\Users\andre\AppData\Local\Temp\ipykernel_38296\2581188008.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['address'] = df_clean["block"].astype(str) + " " + df_clean["street_name"]

,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,remaining_lease,resale_price,address
0,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,61,232000.0,406 ANG MO KIO AVE 10
1,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,60,250000.0,108 ANG MO KIO AVE 4
2,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62,262000.0,602 ANG MO KIO AVE 5
3,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,62,265000.0,465 ANG MO KIO AVE 10
4,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62,265000.0,601 ANG MO KIO AVE 5
...,...,...,...,...,...,...,...,...,...,...
92265,YISHUN,EXECUTIVE,406,YISHUN AVE 6,10 TO 12,148.0,Maisonette,66,655000.0,406 YISHUN AVE 6
92266,YISHUN,EXECUTIVE,355,YISHUN RING RD,10 TO 12,146.0,Maisonette,66,650000.0,355 YISHUN RING RD
92267,YISHUN,EXECUTIVE,364,YISHUN RING RD,01 TO 03,146.0,Maisonette,66,607000.0,364 YISHUN RING RD
92268,YISHUN,EXECUTIVE,828,YISHUN ST 81,01 TO 03,142.0,Apartment,66,670000.0,828 YISHUN ST 81
92269,YISHUN,EXECUTIVE,877,YISHUN ST 81,07 TO 09,145.0,Maisonette,65,660000.0,877 YISHUN ST 81

## Use OneMap API to Get Latitude and Longitude

In [22]:
import requests
import json

def get_onemap_token(email, password):
    """
    Get access token from OneMap API
    """
    auth_url = "https://www.onemap.gov.sg/api/auth/post/getToken"
    
    payload = {
        'email': email,
        'password': password
    }
    
    headers = {
        'Content-Type': 'application/json',
        'User-Agent': 'Your App Name'
    }
    
    try:
        response = requests.post(auth_url, json=payload, headers=headers)
        if response.status_code == 200:
            token_data = response.json()
            return token_data.get('access_token')
        else:
            print(f"Error getting token: {response.status_code}")
            return None
    except Exception as e:
        print(f"Exception getting token: {e}")
        return None

# Replace with your credentials
EMAIL = "andrewphw.24@ichat.sp.edu.sg"
PASSWORD = "mynameJeff01"

access_token = get_onemap_token(EMAIL, PASSWORD)
if access_token:
    print(f"Token obtained: {access_token}")
else:
    print("Failed to get token")

Token obtained: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMDE1NCwiZm9yZXZlciI6ZmFsc2UsImlzcyI6Ik9uZU1hcCIsImlhdCI6MTc2NDk5NDk1MywibmJmIjoxNzY0OTk0OTUzLCJleHAiOjE3NjUyNTQxNTMsImp0aSI6ImU0YjVmOWVlLTVmNTktNDUzNy1iODFlLTc2NDUyMzIyYTRiZiJ9.7RLJ3o7ONNRrODpGCPmmtWw2RZPkUCjecoVsL09Bz_zprOonFCD2G0A49W1WOulL_9qFevI-vK250ycln7CgUlAd583J63J954VwmrVExocnQ6DIn6OEVjMIn6mYjcVGyEcb5QLy2nJe3o1KNaGV6_9GeTyTkqk6CrwQvM3nvE2gHWzQB7M0bl7iUJBee31uCXvCQ6QGpmW9-4iutXVIiaxTcgy8OSANonPWWqJJabd9CojD4wwqd2Ilt402rYGL2PAUt2eOYI8fuT0YlaxzhTjmGCWqDEiC1ksX-A4-T2U47S3O_okXtFAb-UxQ9uUeLM1fkB6jBpngQfUncyvSLw

In [23]:
# Function to get latitude and longitude for a given address
def get_lat_lon(address, token):
    url = (
        "https://www.onemap.gov.sg/api/common/elastic/search"
        f"?searchVal={address}&returnGeom=Y&getAddrDetails=Y&pageNum=1"
    )
    headers = {"Authorization": token}

    r = requests.get(url, headers=headers)
    if r.status_code != 200:
        return None, None

    data = r.json()
    if data["found"] == 0:
        return None, None

    result = data["results"][0]
    return result["LATITUDE"], result["LONGITUDE"]

In [24]:
# -----------------------------
# Geocode UNIQUE addresses with checkpoints
# -----------------------------
# Extract unique addresses
unique_addresses = df_clean["address"].unique()
print("Total unique addresses:", len(unique_addresses))

token = access_token
address_cache = {}

for idx, addr in enumerate(unique_addresses, 1):  # start counting from 1
    lat, lon = get_lat_lon(addr, token)
    address_cache[addr] = (lat, lon)
    
    # Print checkpoint every 500 addresses
    if idx % 500 == 0 or idx == len(unique_addresses):
        print(f"Completed {idx}/{len(unique_addresses)} unique addresses")

# -----------------------------
# Map results back to full dataset
# -----------------------------
df_clean["latitude"] = df_clean["address"].map(lambda x: address_cache[x][0])
df_clean["longitude"] = df_clean["address"].map(lambda x: address_cache[x][1])

Total unique addresses: 8981
Completed 500/8981 unique addresses
Completed 1000/8981 unique addresses
Completed 1500/8981 unique addresses
Completed 2000/8981 unique addresses
Completed 2500/8981 unique addresses
Completed 3000/8981 unique addresses
Completed 3500/8981 unique addresses
Completed 4000/8981 unique addresses
Completed 4500/8981 unique addresses
Completed 5000/8981 unique addresses
Completed 5500/8981 unique addresses
Completed 6000/8981 unique addresses
Completed 6500/8981 unique addresses
Completed 7000/8981 unique addresses
Completed 7500/8981 unique addresses
Completed 8000/8981 unique addresses
Completed 8500/8981 unique addresses
Completed 8981/8981 unique addresses

C:\Users\andre\AppData\Local\Temp\ipykernel_38296\1977097428.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["latitude"] = df_clean["address"].map(lambda x: address_cache[x][0])
C:\Users\andre\AppData\Local\Temp\ipykernel_38296\1977097428.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["longitude"] = df_clean["address"].map(lambda x: address_cache[x][1])

In [27]:
df_clean.to_csv("data/Flat prices geocoded.csv", index=False)

# Basic Model Development

## Data Preparation

In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib

In [33]:
df = pd.read_csv("data/Flat prices geocoded.csv")
print(df.head())

         town flat_type block        street_name storey_range  floor_area_sqm  \
0  ANG MO KIO    2 ROOM   406  ANG MO KIO AVE 10     10 TO 12            44.0
1  ANG MO KIO    3 ROOM   108   ANG MO KIO AVE 4     01 TO 03            67.0
2  ANG MO KIO    3 ROOM   602   ANG MO KIO AVE 5     01 TO 03            67.0
3  ANG MO KIO    3 ROOM   465  ANG MO KIO AVE 10     04 TO 06            68.0
4  ANG MO KIO    3 ROOM   601   ANG MO KIO AVE 5     01 TO 03            67.0

       flat_model  remaining_lease  resale_price                address  \
0        Improved               61      232000.0  406 ANG MO KIO AVE 10
1  New Generation               60      250000.0   108 ANG MO KIO AVE 4
2  New Generation               62      262000.0   602 ANG MO KIO AVE 5
3  New Generation               62      265000.0  465 ANG MO KIO AVE 10
4  New Generation               62      265000.0   601 ANG MO KIO AVE 5

   latitude   longitude
0  1.362005  103.853880
1  1.370966  103.838202
2  1.380709  103.835368
3  1.366201  103.857201
4  1.381041  103.835132

In [34]:
df["location"] = df["town"]
basic_features = ["location", "flat_type", "floor_area_sqm", "remaining_lease"]
target = "resale_price"

X = df[basic_features]
y = df[target]

In [35]:
print(df.head())

         town flat_type block        street_name storey_range  floor_area_sqm  \
0  ANG MO KIO    2 ROOM   406  ANG MO KIO AVE 10     10 TO 12            44.0
1  ANG MO KIO    3 ROOM   108   ANG MO KIO AVE 4     01 TO 03            67.0
2  ANG MO KIO    3 ROOM   602   ANG MO KIO AVE 5     01 TO 03            67.0
3  ANG MO KIO    3 ROOM   465  ANG MO KIO AVE 10     04 TO 06            68.0
4  ANG MO KIO    3 ROOM   601   ANG MO KIO AVE 5     01 TO 03            67.0

       flat_model  remaining_lease  resale_price                address  \
0        Improved               61      232000.0  406 ANG MO KIO AVE 10
1  New Generation               60      250000.0   108 ANG MO KIO AVE 4
2  New Generation               62      262000.0   602 ANG MO KIO AVE 5
3  New Generation               62      265000.0  465 ANG MO KIO AVE 10
4  New Generation               62      265000.0   601 ANG MO KIO AVE 5

   latitude   longitude    location
0  1.362005  103.853880  ANG MO KIO
1  1.370966  103.838202  ANG MO KIO
2  1.380709  103.835368  ANG MO KIO
3  1.366201  103.857201  ANG MO KIO
4  1.381041  103.835132  ANG MO KIO

In [36]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

((72924, 4), (18232, 4))

## Model Training

In [37]:
categorical_cols = ["location", "flat_type"]
numeric_cols = ["floor_area_sqm", "remaining_lease"]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", "passthrough", numeric_cols),
    ]
)

rf_basic = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=100,
        max_depth=20,
        min_samples_leaf=2,
        n_jobs=-1,
        random_state=42
    ))
])

In [38]:
rf_basic.fit(X_train, y_train)
print("Training complete.")

Training complete.

In [39]:
preds = rf_basic.predict(X_test)

mae = mean_absolute_error(y_test, preds)
rmse = mean_squared_error(y_test, preds, squared=False)
r2 = r2_score(y_test, preds)

print("BASIC MODEL EVALUATION")
print("------------------------")
print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

BASIC MODEL EVALUATION
------------------------
MAE : 33430.59404484435
RMSE: 46586.046675217185
R²  : 0.9096712195409657

In [ ]:
joblib.dump(rf_basic, "rf_model_basic.pkl")
print("Saved as rf_model_basic.pkl")

# Precise Model Development

## Data Preparation

In [40]:
df = pd.read_csv("data/Flat prices geocoded.csv")
print(df.head())

         town flat_type block        street_name storey_range  floor_area_sqm  \
0  ANG MO KIO    2 ROOM   406  ANG MO KIO AVE 10     10 TO 12            44.0
1  ANG MO KIO    3 ROOM   108   ANG MO KIO AVE 4     01 TO 03            67.0
2  ANG MO KIO    3 ROOM   602   ANG MO KIO AVE 5     01 TO 03            67.0
3  ANG MO KIO    3 ROOM   465  ANG MO KIO AVE 10     04 TO 06            68.0
4  ANG MO KIO    3 ROOM   601   ANG MO KIO AVE 5     01 TO 03            67.0

       flat_model  remaining_lease  resale_price                address  \
0        Improved               61      232000.0  406 ANG MO KIO AVE 10
1  New Generation               60      250000.0   108 ANG MO KIO AVE 4
2  New Generation               62      262000.0   602 ANG MO KIO AVE 5
3  New Generation               62      265000.0  465 ANG MO KIO AVE 10
4  New Generation               62      265000.0   601 ANG MO KIO AVE 5

   latitude   longitude
0  1.362005  103.853880
1  1.370966  103.838202
2  1.380709  103.835368
3  1.366201  103.857201
4  1.381041  103.835132

In [41]:
df["location"] = df["street_name"]
precise_features = [
    "location",
    "storey_range",
    "flat_type",
    "floor_area_sqm",
    "remaining_lease",
    "latitude",
    "longitude"
]

X = df[precise_features]
y = df[target]

In [42]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

((72924, 7), (18232, 7))

## Model Training

In [43]:
categorical_cols = [
    "location",
    "storey_range",
    "flat_type"
]

numeric_cols = [
    "floor_area_sqm",
    "remaining_lease",
    "latitude",
    "longitude"
]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)

rf_precise = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=50,
        max_depth=20,
        min_samples_leaf=2,
        n_jobs=-1,
        random_state=42
    ))
])

In [44]:
rf_precise.fit(X_train, y_train)
print("Training complete.")

Training complete.

In [45]:
preds = rf_precise.predict(X_test)

mae = mean_absolute_error(y_test, preds)
rmse = mean_squared_error(y_test, preds, squared=False)
r2 = r2_score(y_test, preds)

print("PRECISE MODEL EVALUATION")
print("------------------------")
print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

PRECISE MODEL EVALUATION
------------------------
MAE : 19970.0402589627
RMSE: 28207.27995142473
R²  : 0.9668840781118598

In [ ]:
joblib.dump(rf_precise, "rf_model_precise.pkl")
print("Saved as rf_model_precise.pkl")